Repository jenkinsci/pipeline-build-step-plugin, pull requests merged in 2023-04, with the labels that each got.

#110 Only add WarningAction when propagate: true
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerListener.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java
Labels: bug

#113 Refresh plugin
  Jenkinsfile
  pom.xml
Labels: developer

#112 Mark pipeline waitForBuild step with the downstream build result
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildListener.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/WaitForBuildStepTest.java
Labels: enhancement
