Repository jenkinsci/pipeline-build-step-plugin, pull requests merged in 2025-01, with the labels that each got.

#143 Use `jenkins.baseline` to reduce bom update mistakes
  pom.xml
Labels: chore

#144 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStep.java
Labels: dependencies

#146 De-flake `BuildTriggerStepTest.waitForStart`
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/BuildTriggerStepTest.java
Labels: test
